"""Add performance indexes to User model

Revision ID: 82aaeed101c0
Revises: 96ffb2c2a8e6
Create Date: 2026-07-11 14:14:12.393423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82aaeed101c0'
down_revision: Union[str, None] = '96ffb2c2a8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_templates')
    op.create_index(op.f('ix_users_enrollment_no'), 'users', ['enrollment_no'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_index(op.f('ix_users_total_points'), 'users', ['total_points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_total_points'), table_name='users')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_enrollment_no'), table_name='users')
    op.create_table('certificate_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('design_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('required_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('name_y_percent', sa.INTEGER(), server_default=sa.text('48'), autoincrement=False, nullable=False),
    sa.Column('detail_y_percent', sa.INTEGER(), server_default=sa.text('58'), autoincrement=False, nullable=False),
    sa.Column('font_size', sa.INTEGER(), server_default=sa.text('32'), autoincrement=False, nullable=False),
    sa.Column('font_color', sa.TEXT(), server_default=sa.text("'#1e1e1e'::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('certificate_templates_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('certificate_templates_pkey'))
    )
    # ### end Alembic commands ###
