"""initial_migration

Revision ID: 96ffb2c2a8e6
Revises: None
Create Date: 2026-07-11 11:33:18.413974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96ffb2c2a8e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_resource', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_uploads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('certificate_templates')
    op.add_column('announcements', sa.Column('message', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('type', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('target_group', sa.String(), nullable=True))
    
    # Migrate existing data
    op.execute("UPDATE announcements SET message = content WHERE message IS NULL AND content IS NOT NULL")
    op.execute("UPDATE announcements SET message = '' WHERE message IS NULL")
    op.execute("UPDATE announcements SET target_group = target_audience WHERE target_group IS NULL AND target_audience IS NOT NULL")
    op.execute("UPDATE announcements SET type = 'General' WHERE type IS NULL")
    
    # Make columns non-nullable
    op.alter_column('announcements', 'message', nullable=False)
    op.alter_column('announcements', 'type', nullable=False)

    op.alter_column('announcements', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('announcements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    
    # Drop old columns and constraint safely
    # Check if the foreign key exists before dropping
    try:
        op.drop_constraint('announcements_created_by_fkey', 'announcements', type_='foreignkey')
    except Exception:
        pass
    # Drop old columns and constraint safely using CASCADE to drop dependent RLS policies
    try:
        op.execute("ALTER TABLE announcements DROP COLUMN created_by CASCADE")
    except Exception:
        pass
    try:
        op.execute("ALTER TABLE announcements DROP COLUMN content CASCADE")
    except Exception:
        pass
    try:
        op.execute("ALTER TABLE announcements DROP COLUMN target_audience CASCADE")
    except Exception:
        pass
    op.alter_column('attendance', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('attendance', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('attendance_student_id_date_key'), 'attendance', type_='unique')
    op.create_unique_constraint('uq_student_date_attendance', 'attendance', ['student_id', 'date'])
    op.alter_column('certificates', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('certificates', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('notifications', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('points_history', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('points_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('projects', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('projects', 'instruction_pdf',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('projects', 'assigned_to',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ALL'::text"))
    op.alter_column('projects', 'assigned_target',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('referrals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('referrals_new_student_key'), 'referrals', type_='unique')
    op.create_unique_constraint('uq_new_student_referral', 'referrals', ['new_student'])
    op.add_column('task_submissions', sa.Column('file_upload_id', sa.Uuid(), nullable=True))
    op.add_column('task_submissions', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('task_submissions', 'uploaded_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('task_submissions', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('task_submissions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('task_submissions', 'review_comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('task_submissions_student_id_task_id_key'), 'task_submissions', type_='unique')
    op.create_unique_constraint('uq_student_task_submission', 'task_submissions', ['student_id', 'task_id'])
    op.create_foreign_key(None, 'task_submissions', 'file_uploads', ['file_upload_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tasks', 'rules',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tasks', 'reference_file',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'ALL'::text"))
    op.alter_column('tasks', 'assigned_target',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.add_column('team_invitations', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('team_invitations', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('team_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('team_invitations_team_id_student_id_key'), 'team_invitations', type_='unique')
    op.create_unique_constraint('uq_team_student_invitation', 'team_invitations', ['team_id', 'student_id'])
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('teams', 'team_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('teams', 'mentor',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('teams', 'tagline',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('teams_team_name_key'), 'teams', type_='unique')
    op.create_index(op.f('ix_teams_team_name'), 'teams', ['team_name'], unique=True)
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False, server_default='$2b$12$1E4vcow/yR8uQdT7ncEMc.FjLVPlwn2Cby0f/kx2PC5H17/17.mnu'))
    op.add_column('users', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'Student'::text"))
    op.alter_column('users', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'team',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'photo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'enrollment_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'branch',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'batch',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'skills',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'linkedin',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'github',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'instagram',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_referral_code_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_foreign_key(None, 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_referral_code_key'), 'users', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('users', 'instagram',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'github',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'linkedin',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'skills',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'batch',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'branch',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'enrollment_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'referral_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'photo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'team',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'Student'::text"))
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'team_id')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_teams_team_name'), table_name='teams')
    op.create_unique_constraint(op.f('teams_team_name_key'), 'teams', ['team_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('teams', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('teams', 'tagline',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('teams', 'mentor',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('teams', 'team_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('teams', 'updated_at')
    op.drop_constraint('uq_team_student_invitation', 'team_invitations', type_='unique')
    op.create_unique_constraint(op.f('team_invitations_team_id_student_id_key'), 'team_invitations', ['team_id', 'student_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('team_invitations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('team_invitations', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.drop_column('team_invitations', 'updated_at')
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('tasks', 'assigned_target',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'assigned_to',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ALL'::text"))
    op.alter_column('tasks', 'reference_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'deadline',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'rules',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_constraint(None, 'task_submissions', type_='foreignkey')
    op.drop_constraint('uq_student_task_submission', 'task_submissions', type_='unique')
    op.create_unique_constraint(op.f('task_submissions_student_id_task_id_key'), 'task_submissions', ['student_id', 'task_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('task_submissions', 'review_comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_submissions', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.alter_column('task_submissions', 'comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('task_submissions', 'uploaded_file',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('task_submissions', 'updated_at')
    op.drop_column('task_submissions', 'file_upload_id')
    op.drop_constraint('uq_new_student_referral', 'referrals', type_='unique')
    op.create_unique_constraint(op.f('referrals_new_student_key'), 'referrals', ['new_student'], postgresql_nulls_not_distinct=False)
    op.alter_column('referrals', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('projects', 'assigned_target',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'assigned_to',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ALL'::text"))
    op.alter_column('projects', 'instruction_pdf',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('projects', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('projects', 'updated_at')
    op.alter_column('points_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('points_history', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notifications', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('certificates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('certificates', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('certificates', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_student_date_attendance', 'attendance', type_='unique')
    op.create_unique_constraint(op.f('attendance_student_id_date_key'), 'attendance', ['student_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('attendance', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('announcements', sa.Column('target_audience', sa.TEXT(), server_default=sa.text("'ALL'::text"), autoincrement=False, nullable=False))
    op.add_column('announcements', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('announcements', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('announcements_created_by_fkey'), 'announcements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('announcements', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.alter_column('announcements', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('announcements', 'target_group')
    op.drop_column('announcements', 'type')
    op.drop_column('announcements', 'message')
    # op.create_table('certificate_templates',
    # sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    # sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('design_url', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('required_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    # sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    # sa.Column('name_y_percent', sa.INTEGER(), server_default=sa.text('48'), autoincrement=False, nullable=False),
    # sa.Column('detail_y_percent', sa.INTEGER(), server_default=sa.text('58'), autoincrement=False, nullable=False),
    # sa.Column('font_size', sa.INTEGER(), server_default=sa.text('32'), autoincrement=False, nullable=False),
    # sa.Column('font_color', sa.TEXT(), server_default=sa.text("'#1e1e1e'::text"), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('certificate_templates_created_by_fkey'), ondelete='SET NULL'),
    # sa.PrimaryKeyConstraint('id', name=op.f('certificate_templates_pkey'))
    # )
    op.drop_table('file_uploads')
    op.drop_table('audit_logs')
    op.drop_table('settings')
    # ### end Alembic commands ###
